### ISSUE TITLE
I find this module unusable

### ISSUE THREAD

**Issue by moshest** [stopwords-iso/stopwords-en#1]
Why the word "line" is on the list?

I think this list is way too large. Check out npm module "[stopword](https://www.npmjs.com/package/stopword)" for better reference.

**Comment by Berkmann18** [comment]
It is, things like "10", "39", "computer" and a lot of the rest I've seen are not stopwords.

**Comment by genediazjr** [comment]
Hi, sorry for the very late response. The sources of the words are included. I'm open to a pr if you see that some of it should not be included. Thanks!
